ALTER TABLE public.site_visits
DROP COLUMN IF EXISTS width,
DROP COLUMN IF EXISTS height,
DROP COLUMN IF EXISTS depth,
DROP COLUMN IF EXISTS installation_height,
DROP COLUMN IF EXISTS photos,
DROP COLUMN IF EXISTS legacy_photo_categories,
DROP COLUMN IF EXISTS power_available_legacy,
DROP COLUMN IF EXISTS existing_signage,
DROP COLUMN IF EXISTS complexity,
DROP COLUMN IF EXISTS notes,
DROP COLUMN IF EXISTS customer_notes,
DROP COLUMN IF EXISTS visit_date,
DROP COLUMN IF EXISTS visit_time,
DROP COLUMN IF EXISTS site_address,
DROP COLUMN IF EXISTS site_type,
DROP COLUMN IF EXISTS contact_number,
DROP COLUMN IF EXISTS special_instructions;
